name:                api-common
version:             0.1.3.4
github:              "learnew2/api-common"
license:             BSD-3-Clause
author:              "Ilya Zamaratskikh"
maintainer:          "mrtstg@yandex.ru"
copyright:           "2025 Ilya Zamaratskikh"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/learnew2/api-common#readme>

dependencies:
- base >= 4.7 && < 5
- servant-client == 0.19
- servant-server == 0.19.2
- http-conduit == 2.3.8.1
- aeson == 2.1.2.1
- transformers == 0.5.6.2
- mtl == 2.2.2
- text == 2.0.2
- bytestring == 0.11.5.2
- http-types == 0.12.3
- monad-logger == 0.3.40
- servant == 0.19.1
- exceptions == 0.10.5
- connection == 0.3.1
- keycloak-api

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  api-common-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-common
