name:                api-codegen
version:             0.1.0.0
github:              "learnew2/api-codegen"
license:             BSD-3-Clause
author:              "Ilya Zamaratskikh"
maintainer:          "mrtstg@yandex.ru"
copyright:           "2025 Ilya Zamaratskikh"

dependencies:
- base >= 4.7 && < 5
- filepath == 1.4.2.2
- text == 2.0.2
- servant-js
- api-common

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  api-codegen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
